### ISSUE TITLE
No way to return to "Search or enter address"

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/firefox-echo-show#140] opened 2018-11-16 18:39 UTC
Perhaps this is desired behavior.  Is the "Search or enter address" prompt merely a first time use thing?  If so, then this issue can be closed.

## Steps to reproduce
1. Open Firefox
2. Open a website:  i.e. Wikipedia
3. Observe URL bar reads: "wikipedia.org"
4. Try to back arrow to default screen where URL bar reads "Search or enter address"

### Expected behavior
5. Pressing back button or home button would reset the URL bar to read "Search or enter address"

### Actual behavior
5. URL bar is stuck with first address entered as base address

### Work around
Clear site cookies resets URL bar

### Device information
* Echo Show device (2nd gen, build #625531610)
* Firefox version: 1.2

**Comment by aminalhazwani** [comment] 2018-11-19 11:32
Is this a dupe of #25? @rpappalax we added further details here https://github.com/mozilla-mobile/firefox-echo-show/issues/25#issuecomment-439130484

**Comment by athomasmoz** [comment] 2018-11-22 17:16
Closing as dup of #25

**Closed by athomasmoz** 2018-11-22 17:16 UTC
